# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap
    - jekyll-paginate

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh, github_issue_generator.rb]

# Permalinks
permalink: /:title/

# Site
title: 'Mborgbo'
description: 'mborgbo: musings and yawning by Jibrin Jaafaru'
url: https://mborgbo.github.io
logo: /img/logo.png
timezone: America/Los_Angeles

repo_name: mborgbo.github.io

twitter:
    username: jbrnjfr

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/jbrnjfr'
    github: 'https://github.com/mborgbo/mborgbo.github.io'
    issue: 'https://github.com/Smborgbo/mborgbo.github.io/issues/new'
    pull: 'https://github.com/mborgbo/mborgbo.github.io/compare'


paginate: 25
paginate_path: "/page:num/"
